name: CI
on:
  push:
    branches:
      - master
      - develop
      - "release/**"
jobs:
  buildAndTest:
    name: build and test
    runs-on: macos-latest
    strategy:
      matrix:
        project: ["XiphiasNet.xcodeproj"]
        scheme: ["XiphiasNet"]
        destination: ["platform=iOS Simulator,name=iPhone 11"]
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild test -enableCodeCoverage YES -project "${project}" -scheme "${scheme}" -destination "${destination}" ONLY_ACTIVE_ARCH=YES | xcpretty || exit 1
        env:
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
          project: ${{ matrix.project }}